apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 4
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: 925774240266.dkr.ecr.us-east-1.amazonaws.com/backend:4
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: db_host
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: db_user
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DB_NAME
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: PORT
        - name: APP_PORT
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: APP_PORT
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: NODE_ENV
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: JWT_SECRET
        - name: JWT_EXPIRES_IN
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: JWT_EXPIRES_IN
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: db_password
