apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  DB_NAME: "booksapp"
  PORT: "3306"
  APP_PORT: "80"
  NODE_ENV: "development"
  JWT_SECRET: "sdfghjkldfcgvhjnk"
  JWT_EXPIRES_IN: "7d"
