apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: 545009827818.dkr.ecr.ap-south-1.amazonaws.com/frontend:14
        ports:
        - containerPort: 80
          # env:
          # - name: REACT_APP_API_BASE_URL
          # value: "http://3.111.197.160:31005"

---
apiVersion: v1
kind: Service
metadata: 
  name: frontend
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
      #    nodePort: 31004  # Optional: Specify a nodePort if you want a fixed port
  selector:
    app: frontend  # Ensure this matches the labels in the Deployment
  type: LoadBalancer

