apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  db_host: Ym9va3MuYzZyb3dzMG9veXBhLnVzLWVhc3QtMS5yZHMuYW1hem9uYXdzLmNvbQ==
  db_user: YWRtaW4=
  db_password: Q2xvdWQxMjM=
